### PR TITLE
Add Indonesian Translation

### PR DESCRIPTION
**Pull request by ilhamsyahids**
Add Indonesian. Another collection of translations!

### CODE REVIEW

**Comment by icabetong** [comment]
that's nice. thank you for adding another translation. I'll review it when I get home. :)

**Comment by ilhamsyahids** [comment]
Thank you for approving it. Can you add Indonesian into README?

**Comment by icabetong** [comment]
Yeah. I forgot about that, what name should I add in for your contribution?

**Comment by ilhamsyahids** [comment]
Please, Ilham Syahid S

**Pull request merged**
